<a href="https://colab.research.google.com/github/00-Vinaylohar-00/AI_2026_AI/blob/main/Assignments_07_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Assignments
'''first 2 rows
last 2 rows
9,10,11
8,9,12,13
last 2 coloumns
middle 2 coloumns
5,6 13,14
4,8,7,11'''


In [ ]:
import numpy as np
a=np.arange(30).reshape(6,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
def deviation(x,a):
    return (x-a.mean())/ a.std()

a=np.arange(30).reshape(6,5)
x=5
g=deviation(x,a)
g

np.float64(-1.0975754450695303)

In [ ]:
a[[0,1]] # to acess rows of the data

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[[-1,-2]] # To access last rows of the data

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24]])

In [ ]:
a[-2][2:5] # To access specific row data with specific element

array([22, 23, 24])

In [ ]:
a[4:6, 0:2] # To access specific rows data with specific elements

array([[20, 21],
       [25, 26]])

In [ ]:
print(a)
print(a[:,3:5]) # To access last two coloumn of the data

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 3  4]
 [ 8  9]
 [13 14]
 [18 19]
 [23 24]
 [28 29]]


In [ ]:
print(a)
print(a[:,1:4]) # To access Middle three column elemnts of the data

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]
 [16 17 18]
 [21 22 23]
 [26 27 28]]


In [4]:
import numpy as np
a=np.arange(30).reshape(6,5)
print(a)
print(a[0,2:4],a[4,:2]) # to access random rows elements from data

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[2 3] [20 21]


In [9]:
print(a)
print([a[1:3,4],a[3:5,0]]) # to access random coloumns elememts from the data

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
[array([ 9, 14]), array([15, 20])]
